# Generated by Django 2.0.6 on 2018-07-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_auto_20180708_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='liked_num',
            field=models.IntegerField(default=0),
        ),
    ]
